### ISSUE TITLE
支持多数据源下的初始化数据的SQL脚本吗？

### ISSUE THREAD

**Issue by waylau** [mybatis-flex/mybatis-flex#510]
类似于Spring的spring.sql.init配置

```
spring.sql.init.data-locations=classpath:sql/data.sql
spring.sql.init.schema-locations=classpath:sql/schema.sql
```

例如，可以这样？

```
# 多数据源配置
mybatis-flex:
  datasource:
    ds1-datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
      username: sa
      password:
      schema-locations: classpath:ds1-schema.sql
      data-locations: classpath:ds1-data.sql
    ds2-datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
      username: sa
      password:
      schema-locations: classpath:ds2-schema.sql
      data-locations: classpath:ds2-data.sql
```
